2020-05-26 21:05:28,422 ERROR: Exception on /edit_profile [POST] [in /home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/app/routes.py", line 92, in edit_profile
    db.session.commit()
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 230, in save_obj
    _emit_update_statements(
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 994, in _emit_update_statements
    c = cached_connections[connection].execute(
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1020, in execute
    return meth(self, multiparams, params)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1323, in _execute_context
    self._handle_dbapi_exception(
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1517, in _handle_dbapi_exception
    util.raise_(
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "/home/thelink/Documents/aulas/copa_transparente/blog/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('vinicius', 'Oi, sou programador e um cara legal, eu acho...\r\nmuito top', 4)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-05-26 21:11:02,592 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:23:02,237 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:23:10,084 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:23:49,831 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:24:04,997 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:24:09,157 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:24:50,820 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:25:10,593 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:26:34,080 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:26:43,283 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:26:47,054 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:26:56,120 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:28:30,824 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:30:57,394 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:30:59,758 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:31:01,590 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:31:22,159 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:32:27,249 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:32:29,332 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:34:08,183 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:35:11,322 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:44]
2020-05-26 21:38:47,414 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:46]
2020-05-26 21:39:48,128 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:46]
2020-05-26 21:39:55,777 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:46]
2020-05-26 21:40:30,990 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:46]
2020-05-26 21:41:25,111 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:46]
2020-05-26 21:41:29,228 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:46]
2020-05-26 21:41:31,563 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:46]
2020-05-26 21:42:01,120 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:46]
2020-05-26 21:43:06,066 INFO: Microblog Iniciando!!! [in /home/thelink/Documents/aulas/copa_transparente/blog/app/__init__.py:46]
